/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author pjroj
 */
public class VentanaUsers extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsers
     */
    public VentanaUsers() {
        initComponents();
        setSize(340,440);
        setResizable(false);
        setTitle("Administrar Usuarios");
        setLocationRelativeTo(null);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fondo1 = new javax.swing.JPanel();
        Fondo2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        EliminateUsersButton = new javax.swing.JButton();
        UsersButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 96, -1, -1));

        Fondo1.setBackground(new java.awt.Color(153, 255, 255));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 440));

        Fondo2.setBackground(new java.awt.Color(102, 153, 255));
        Fondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Usuarios");
        Fondo2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 40));

        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Fondo2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Administración de");
        Fondo2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 220, 40));

        ReturnButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReturnButton.setText("Volver al menú de inicio");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });
        Fondo2.add(ReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, 30));

        EliminateUsersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EliminateUsersButton.setText("Eliminar usuario");
        EliminateUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminateUsersButtonActionPerformed(evt);
            }
        });
        Fondo2.add(EliminateUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, 40));

        UsersButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsersButton4.setText("Crear usuario");
        UsersButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButton4ActionPerformed(evt);
            }
        });
        Fondo2.add(UsersButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, 40));

        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        VentanaInicio inicio = new VentanaInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void EliminateUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminateUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminateUsersButtonActionPerformed

    private void UsersButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsersButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminateUsersButton;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton UsersButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
