/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author pjroj
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setSize(720,440);
        setResizable(false);
        setTitle("Inicio - Cargar archivos");
        setLocationRelativeTo(null);
        this.repaint();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        ImpressionButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        UsersControllerButton = new javax.swing.JButton();
        documentsButton = new javax.swing.JButton();
        Fondo1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Elija lo que desea hacer a continuación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 230, 30));

        ImpressionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ImpressionButton.setText("Ver cola de impresión");
        ImpressionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpressionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ImpressionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 290, 60));

        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 50, -1));

        UsersControllerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsersControllerButton.setText("Adminstrar usuarios");
        UsersControllerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersControllerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UsersControllerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 290, 60));

        documentsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        documentsButton.setText("Adminstrar documentos del usuario");
        documentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(documentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 290, 60));

        Fondo1.setBackground(new java.awt.Color(153, 255, 255));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Cola de Impresión");
        Fondo1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, 40));
        jLabel3.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 440));

        Fondo2.setBackground(new java.awt.Color(102, 153, 255));
        Fondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 390, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImpressionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpressionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImpressionButtonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void UsersControllerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersControllerButtonActionPerformed
        VentanaUsers usercontroller = new VentanaUsers();
        usercontroller.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UsersControllerButtonActionPerformed

    private void documentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentsButtonActionPerformed
        VentanaDocument documentcontroller = new VentanaDocument();
        documentcontroller.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_documentsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JButton ImpressionButton;
    private javax.swing.JButton UsersControllerButton;
    private javax.swing.JButton documentsButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void setRetavible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
